/*
 * Integra Advisory Partners: site configuration
 *
 * Fill in the values below when the client shares them.
 * Anything left empty ('' or []) stays hidden on the site, so nothing breaks.
 */

const siteConfig = {
  /* ---------- contact details ---------- */
  // TODO: client to supply the real business email. Left empty on purpose so
  // the placeholder address is never published; the site hides it until set.
  contact: {
    email: 'doha@gmail.com',
    phone: '+91 98765 41230',
    address:
      'Zone 61, Al Dafna, Doha, Qatar',
  },

  /* ---------- whatsapp (digits only, with country code) ---------- */
  whatsapp: {
    number: '919876541230',
    message: 'Hello Integra, I would like to learn more about entering Qatar and the GCC.',
  },

  /* ---------- social links (full URLs) ---------- */
  social: {
    linkedin: 'https://www.linkedin.com/',
    instagram: 'https://www.instagram.com/',
    x: 'https://x.com/',
    facebook: 'https://www.facebook.com/',
    youtube: 'https://www.youtube.com/',
  },

  /* ---------- booking + video call (Calendly or similar) ---------- */
  booking: {
    url: 'https://calendly.com/zeeshandivanextechnologies',
  },

  /*
   * ---------- google forms ----------
   * action: the form's "formResponse" URL
   *   (https://docs.google.com/forms/d/e/FORM_ID/formResponse)
   * fields: map each website field name to the Google Form "entry.XXXX" id
   * viewUrl: the public form link (used for Register Interest buttons)
   */
  googleForms: {
    contact: {
      action:
        'https://docs.google.com/forms/d/e/1FAIpQLSer1rCPs516hO7ICSuT4eUQFFP2v0FuhxYTOAmSR61FeIMimQ/formResponse',
      fields: {
        inquiryType: 'entry.1571110673',
        name: 'entry.526797033',
        email: 'entry.1047342294',
        company: 'entry.819956255',
        role: 'entry.1636811960',
        message: 'entry.808375202',
      },
    },
    intake: {
      action:
        'https://docs.google.com/forms/d/e/1FAIpQLSd-24fLNmp1YGwQ3WS5r8g8Ca6dfolWwV-2f_wpGfajik1PTQ/formResponse',
      fields: {
        name: 'entry.2104664601',
        email: 'entry.1158545637',
        company: 'entry.77940272',
        role: 'entry.2089416962',
        origin: 'entry.554513365',
        sector: 'entry.876195094',
        markets: 'entry.7075385',
        budget: 'entry.1282595326',
        documents: 'entry.1610922256',
        timeline: 'entry.84894969',
        concern: 'entry.925730649',
      },
    },
    events: {
      viewUrl:
        'https://docs.google.com/forms/d/e/1FAIpQLSfUt3iDpUlL40SIlc9tsQ7LYE5jO62Kxy3vORg-ep5n_o4rNA/viewform', // Register Interest form link
    },
  },

  /* ---------- secure document upload (Google Form, Jotform, Tally...) ---------- */
  documentUpload: {
    // url: 'https://tally.so/r/EkyMa2',
    url: '',
  },

  /* ---------- mailing list (Mailchimp / Brevo embed form action URL) ---------- */
  mailingList: {
    // Brevo sign-up form "Monthly Brief" (Marketing > Forms)
    action:
      'https://d21b4610.sibforms.com/v2/serve/MUIFAFpxDc3IeDq57294mJVo0pJDr7JVj7wYmhByfoZrtnYF92HSf5bCkmhz6frh-j1iSTR-9Yyixaq4dBTJtavnEoc-FJHWvyCwNZi4m6ndzTl8VPfd__er1v_xK0SKtG91CZbeN2Qfro7J7_poOUx7Fpp10cpw3moKF3IORgSX8hHURb2IhP4y7yldgunnWvEtlG0lN2QdDVibqw==',
    emailField: 'EMAIL',
    // extra fields the provider expects (Brevo: empty spam trap + language)
    hiddenFields: {
      email_address_check: '',
      locale: 'en',
    },
  },

  /* ---------- stripe payment links, keyed by package name ----------
   * A package shows its "Pay Now" button only when its link below is set.
   * Links are created in the Stripe Dashboard (Payment Links > New), which
   * is why they live here rather than being generated by the site.
   *
   * PENDING: the three empty links below still need to be created in Stripe:
   *   Market Entry Blueprint .......................... $5,000
   *   Qatar Incorporation & Bank Readiness Pathway .... $15,000
   *   Operational Readiness Program ................... $30,000
   *
   * The two links that are set are still TEST mode. Switch Stripe to live
   * mode before taking real payments.
   */
  payments: {
    'Executive Discovery Sessions': 'https://buy.stripe.com/test_9B69AV37f9PF7QV9dL4wM00',
    'Market Entry Blueprint': '', // pending: $5,000
    'Qatar Incorporation & Bank Readiness Pathway': '', // pending: $15,000
    'Operational Readiness Program': '', // pending: $30,000
    'Executive Advisory Retainer': 'https://buy.stripe.com/test_3cIbJ3gY5ge32wBfC94wM01',
  },

  /*
   * ---------- project deposit (Process step 5) ----------
   * A Stripe Payment Link where the client enters the deposit amount from
   * their proposal. In Stripe, set "After payment" to redirect to
   * https://<your-domain>/payment-success
   */
  deposit: {
    url: 'https://buy.stripe.com/test_fZu3cx8rzaTJ3AF3Tr4wM02',
  },

  /* ---------- intake budget ranges (leave empty to keep a text box) ---------- */
  // Matches the Packages page price points. Pending client confirmation.
  budgetRanges: [
    'Under $5,000',
    '$5,000 – $15,000',
    '$15,000 – $30,000',
    '$30,000+',
    'Monthly retainer ($2,500+/month)',
    'Not sure yet',
  ],

  /* ---------- hero video (file in /public or full URL) ---------- */
  heroVideo: {
    src: '/hero_video_01.mp4',
    poster: '/images/hero-poster.webp',
  },
}

export default siteConfig
